[username]
style_user = "yellow bold"
style_root = "white bold"
format = "[$user]($style) "
disabled = false
show_always = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false

[git_branch]
symbol = "ðŸŒ± "
style = "bold green"

[custom.arch]
command = "uname -m"
when = """ test $(uname -m) = "x86_64" """
style = "bold yellow"
format = "[$output]($style)"

[time]
disabled = false
format = '[ðŸ•™ $time]($style) '
time_format = "%T"

[aws]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[git_status]
style = "bold white"
conflicted = " ðŸ’¥ "
ahead = " ðŸŽðŸ’¨ "
behind = " ðŸ’¨ "
diverged = " ðŸš€ "
up_to_date = " ðŸŒ "
untracked = " ðŸ›¸ "
stashed = " ðŸŒž "
modified = " ðŸ›° "
staged = '[++\($count\)](green)'
renamed = " ðŸŒ‘ "
deleted = " ðŸ—‘ "
