[username]
style_user = "yellow bold"
style_root = "white bold"
format = "[$user]($style) "
disabled = false
show_always = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"

[directory]
truncation_length = 100
truncate_to_repo = false

[git_branch]
symbol = "ğŸŒ± "
style = "bold green"

[custom.arch]
command = "uname -m"
when = """ test $(uname -m) = "x86_64" """
style = "bold yellow"
format = "[$output]($style)"

[time]
disabled = false
format = '[ğŸ•™ $time]($style) '
time_format = "%T"

[aws]
disabled = true

[nodejs]
disabled = true

[ruby]
disabled = true

[package]
disabled = true

[git_status]
style = "bold white"
conflicted = " ğŸ’¥ "
ahead = " ğŸğŸ’¨ "
behind = " ğŸ’¨ "
diverged = " ğŸš€ "
up_to_date = " ğŸŒ "
untracked = " ğŸ›¸ "
stashed = " ğŸŒ "
modified = " ğŸ‘¾ "
staged = '[++\($count\)](green)'
renamed = " ğŸŒš "
deleted = " ğŸ—‘ "

[battery]
full_symbol = "ğŸŒ• "
charging_symbol = "ğŸŒ” "
discharging_symbol = "ğŸŒ“ "
unknown_symbol = "ğŸª "
empty_symbol = "ğŸŒ‘ "

[[battery.display]]
threshold = 30
style = "bold yellow"
discharging_symbol = "ğŸŒ˜ "

[[battery.display]]
threshold = 20
style = "bold red"
discharging_symbol = "ğŸŒ˜ "
